# Generated by Django 4.1.1 on 2022-10-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='number_answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='number_question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='variant_answer',
        ),
    ]
