# Generated by Django 4.1.1 on 2022-10-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='questions',
            table='quest',
        ),
    ]
