# Generated by Django 4.1.1 on 2022-10-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_questions_options_alter_questions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
