# Generated by Django 4.1.1 on 2022-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_questions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('note', models.TextField()),
                ('next_question', models.IntegerField()),
            ],
            options={
                'db_table': 'answers',
                'managed': True,
            },
        ),
    ]
