# Generated by Django 4.1.1 on 2022-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_answers_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='next_question',
            field=models.IntegerField(null=True),
        ),
    ]
