# Generated by Django 4.1.1 on 2022-10-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_answers_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
