# Generated by Django 4.1.1 on 2022-10-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_answers_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
    ]
