# Generated by Django 4.1.1 on 2022-10-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_rename_question_id_answers_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=250, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.questions'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
