# Generated by Django 4.1.1 on 2022-10-06 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_remove_answers_question_answers_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.questions'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='next_question',
            field=models.IntegerField(null=True),
        ),
    ]
