# Generated by Django 4.1.1 on 2022-10-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_remove_answers_question_id_answers_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='question_st',
        ),
    ]
