# Generated by Django 4.1.1 on 2022-10-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_rename_question_questions_question_st'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_st',
            new_name='question',
        ),
    ]
