# Generated by Django 4.1.1 on 2022-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_rename_question_st_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_final',
            field=models.CharField(default='итоговый ответ', max_length=250, verbose_name='Итоговый ответ'),
            preserve_default=False,
        ),
    ]
