# Generated by Django 3.2.15 on 2022-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='Next_Quest',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
