# Generated by Django 3.2.15 on 2022-10-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0002_alter_answers_next_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='FinalAnswer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='Link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='LinkText',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
