# Generated by Django 3.2.15 on 2022-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0003_auto_20221004_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='Next_Quest',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
