# Generated by Django 3.2.15 on 2022-10-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0005_alter_answers_next_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='LinkText',
        ),
        migrations.AddField(
            model_name='answers',
            name='SecondText',
            field=models.TextField(blank=True),
        ),
    ]
