# Generated by Django 3.2.15 on 2022-10-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0006_auto_20221007_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='SecondAnswerText',
            field=models.TextField(blank=True),
        ),
    ]
