# Generated by Django 3.2.15 on 2022-10-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0007_answers_secondanswertext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='SecondAnswerText',
        ),
    ]
