# Generated by Django 3.2.15 on 2022-10-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0009_answers_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('Next_Item', models.PositiveIntegerField(blank=True, null=True)),
                ('SecondText', models.TextField(blank=True)),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotBack.types')),
            ],
        ),
    ]
