# Generated by Django 3.2.15 on 2022-10-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0010_items_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
