# Generated by Django 3.2.15 on 2022-10-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0012_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='FinalAnswer',
            field=models.TextField(blank=True),
        ),
    ]
