# Generated by Django 3.2.15 on 2022-10-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0013_items_finalanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Next_Item',
            new_name='Next_Quest',
        ),
        migrations.AlterField(
            model_name='items',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
