# Generated by Django 3.2.15 on 2022-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0014_auto_20221013_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Link',
            field=models.TextField(blank=True),
        ),
    ]
