# Generated by Django 3.2.15 on 2022-10-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0015_items_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ_Q_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotBack.faq_types')),
            ],
        ),
    ]
