# Generated by Django 3.2.15 on 2022-10-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0018_faq_priv_q_a_faq_priv_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_priv_q_a',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotBack.faq_priv_types'),
        ),
    ]
