# Generated by Django 3.2.15 on 2022-10-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotBack', '0019_alter_faq_priv_q_a_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_priv_q_a',
            name='Link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq_q_a',
            name='Link',
            field=models.TextField(blank=True),
        ),
    ]
